Repository perftool-incubator/crucible, pull requests merged in 2024-07, with the labels that each got.

#349 Dev kmr
  .github/workflows/crucible-ci.yaml
  .github/workflows/crucible-merged.yaml
  .github/workflows/crucible-scheduled.yaml
  .github/workflows/faux-crucible-ci.yaml
Labels: enhancement

#350 correct syntax in crucible-scheduled workflow
  .github/workflows/crucible-scheduled.yaml
Labels: bug

#352 add python3-requests to the controller image for making HTTP requests
  workshop/controller-workshop.json
Labels: enhancement

#355 Fix crucible-release workflow syntax
  .github/workflows/crucible-release.yaml
Labels: bug, enhancement

#356 add run-crucible-tracking.yaml
  .github/workflows/ci.yaml
  .github/workflows/crucible-ci.yaml
  .github/workflows/crucible-merged.yaml
  .github/workflows/faux-ci.yaml
  .github/workflows/faux-crucible-ci.yaml
  .github/workflows/run-crucible-tracking.yaml
Labels: enhancement

#363 add ilab and nvidia
  config/default_subprojects
Labels: rhel-ai
